# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qna_topic.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'qna_topic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fqna_topic.proto\x12\x07qtopics\"_\n\x0eTopicQuestions\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x18\n\x10static_questions\x18\x02 \x03(\t\x12\x14\n\x0c\x61i_questions\x18\x03 \x03(\t\x12\x0e\n\x06merged\x18\x04 \x03(\t\"I\n\tCachedQnA\x12\'\n\x06topics\x18\x01 \x03(\x0b\x32\x17.qtopics.TopicQuestions\x12\x13\n\x0bsuggestions\x18\x02 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qna_topic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOPICQUESTIONS']._serialized_start=28
  _globals['_TOPICQUESTIONS']._serialized_end=123
  _globals['_CACHEDQNA']._serialized_start=125
  _globals['_CACHEDQNA']._serialized_end=198
# @@protoc_insertion_point(module_scope)
